spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lifepath
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always

server:
  port: 8080
